language: python
sudo: false

python:
  - 2.7

install:
    - touch service.key service.cert service.xml robotkey.pem robotcert.crt
    - make bootstrap-cfy

script:
    - make test

notifications:
  email:
    - holer@ics.muni.cz
    - ljocha@ics.muni.cz
